### ISSUE TITLE
lookupcomputecluster causes panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jcpowermac** [pulumi/pulumi-vsphere#76]
I have tried multiple ways around this all fail

```golang
if dc != nil && dc.Id != "" {
			args := new(vsphere.LookupComputeClusterArgs)
			args.DatacenterId = &dc.Id
			//args.Name = "/" + datacenterName + "/host/" + clusterName
			args.Name = clusterName

			computeCluster, err := vsphere.LookupComputeCluster(ctx, args, nil)

			//computeCluster, err := vsphere.GetComputeCluster(ctx, clusterName, nil, nil, nil)

			if err != nil {
				return err
			}
			spew.Dump(computeCluster)
		}
```

Error
```
  pulumi:pulumi:Stack (okd-pulumi-vsphere-upi-upi):
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xabeb4d]
    goroutine 1 [running]:
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.(*Context).Invoke(0xc00026a200, 0x141d889, 0x31, 0x114e540, 0xc000282200, 0x114e580, 0xc000326180, 0xc00031fba8, 0x1, 0x1, ...)
        /var/home/jcallen/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.0.0/go/pulumi/context.go:155 +0x17d
    github.com/pulumi/pulumi-vsphere/sdk/v2/go/vsphere.LookupComputeCluster(0xc00026a200, 0xc000282200, 0xc00031fba8, 0x1, 0x1, 0xc00025a940, 0x0, 0x0)
        /var/home/jcallen/go/pkg/mod/github.com/pulumi/pulumi-vsphere/sdk/v2@v2.2.1/go/vsphere/getComputeCluster.go:12 +0xaf
    main.main.func1(0xc00026a200, 0x1404b92, 0x13)
        /var/home/jcallen/Development/okd-pulumi-vsphere-upi/main.go:31 +0x517
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.RunWithContext(0xc00026a200, 0x1433630, 0xc00003a1bf, 0x16)
        /var/home/jcallen/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.0.0/go/pulumi/run.go:101 +0x1ff
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.RunErr(0x1433630, 0x0, 0x0, 0x0, 0x0, 0x0)
        /var/home/jcallen/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.0.0/go/pulumi/run.go:82 +0x20a
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.Run(0x1433630, 0x0, 0x0, 0x0)
        /var/home/jcallen/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.0.0/go/pulumi/run.go:39 +0x59
    main.main()
        /var/home/jcallen/Development/okd-pulumi-vsphere-upi/main.go:12 +0x3e
    exit status 2
 
    error: an unhandled error occurred: program exited with non-zero exit code: 1
```

**Comment by stack72** [comment]
Hi @jcpowermac 

I believe that the code should look as follows:

```
if dc != nil && dc.Id != "" {
	args := &vsphere.LookupComputeClusterArgs{
        args.DatacenterId = &dc.Id,
		args.Name = clusterName
    }

    computeCluster, err := vsphere.LookupComputeCluster(ctx, args, nil)
	if err != nil {
		return err
	}
}
```
Notice the use of passing a pointer to the LookupComputeCluster func

**Comment by jcpowermac** [comment]
Thansk for responding @stack72 

`new()` allocates and creates a pointer

Alternatively tried this
```
			args := &vsphere.LookupComputeClusterArgs{
				DatacenterId: &dc.Id,
				Name:         clusterName,
			}
```
same result

**Comment by stack72** [comment]
lastly, I should have written an update - notice that there is no need to pass a nil as the invoke args

```
computeCluster, err := vsphere.LookupComputeCluster(ctx, args)
```

**Comment by jcpowermac** [comment]
@stack72 that was the problem...the `nil`
thanks!

**Comment by lukehoban** [comment]
> notice that there is no need to pass a nil as the invoke args

And in particular, the panic reported initially above is due to passing a `nil` option here.  I will open an issue to track a better error message for that.

**Comment by stack72** [comment]
@jcpowermac sorry that you hit this - I just opened this issue in our docs repo https://github.com/pulumi/docs/issues/3192

The example wasn't very useful to you here

**Comment by jcpowermac** [comment]
@stack72 no worries, just working through it.  So far I am really liking pulumi.
Thanks for the quick responses!

**Comment by stack72** [comment]
Thanks - please continue opening any issues you find :)
